<?php

namespace Tests;

use Pcache\Driver\Memcached;

class MemcachedDriverTest extends CacheDriverBase
{
    protected $cacheDriver = Memcached::class;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
